import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';
import {allowedOrigin,payload,record,snapshot,ACTIVE_MS} from '../functions/_presence.js';import {onRequest} from '../functions/api/presence.js';
class Statement{constructor(s){this.s=s;this.v=[]}bind(...v){this.v=v;return this}first(){return this.s.get(...this.v)||null}all(){return {results:this.s.all(...this.v)}}run(){return this.s.run(...this.v)}}
class D1{constructor(){this.db=new DatabaseSync(':memory:')}prepare(sql){return new Statement(this.db.prepare(sql))}exec(sql){this.db.exec(sql)}}
const sid='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',page='bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',page2='cccccccc-cccc-4ccc-cccc-cccccccccccc';
function env(){const AUTH_DB=new D1();AUTH_DB.exec(fs.readFileSync(new URL('../migrations/0005_live_presence.sql',import.meta.url),'utf8'));return {AUTH_DB}}
const req=new Request('https://www.admiranext.com/api/presence',{headers:{'User-Agent':'Mozilla/5.0'}});
test('orígenes exactos y rutas sin queries: no dominios ni credenciales arbitrarias',()=>{assert.equal(allowedOrigin('https://www.digitalsignage.ai'),'https://www.digitalsignage.ai');assert.equal(allowedOrigin('https://evil.digitalsignage.ai'),null);assert.equal(allowedOrigin('https://digitalsignage.ai.evil.test'),null);assert.equal(allowedOrigin('http://digitalsignage.ai'),null);assert.throws(()=>payload({sid,page,action:'ping',path:'/page?token=secret'}));assert.throws(()=>payload({sid,page,action:'ping',path:'//evil.test'}));});
test('navegación y salida tardía de un documento no borran la página siguiente',async()=>{const e=env();await record(e,req,'digitalsignage.ai',{sid,page,path:'/studio/',action:'ping'},100000);await record(e,req,'digitalsignage.ai',{sid,page:page2,path:'/biz/',action:'ping'},105000);await record(e,req,'digitalsignage.ai',{sid,page,action:'leave'},106000);const r=await snapshot(e,'',110000);assert.equal(r.online,1);assert.equal(r.pages[0].path,'/biz/');assert.equal(r.visitors[0].visitor,'Visitante aaaaaaaa');assert.equal(JSON.stringify(r).includes(sid),false)});
test('caducidad, aislamiento por dominio y varias páginas de una sesión',async()=>{const e=env();await record(e,req,'digitalsignage.ai',{sid,page,path:'/',action:'ping'},100000);await record(e,req,'digitalsignage.ai',{sid,page:page2,path:'/biz/',action:'ping'},100000);assert.equal((await snapshot(e,'digitalsignage.ai',110000)).online,1);assert.equal((await snapshot(e,'admiranext.com',110000)).online,0);assert.equal((await snapshot(e,'',100000+ACTIVE_MS+1)).online,0);assert.equal(e.AUTH_DB.prepare('SELECT count(*) AS n FROM admiranext_presence').first().n,0)});
test('API pública sólo recibe pings; la lectura de presencia sigue privada',async()=>{const e=env();assert.equal((await onRequest({request:new Request(req.url),env:e})).status,401);const ping={sid,page,path:'/store/',action:'ping'};const request=new Request(req.url,{method:'POST',headers:{Origin:'https://www.digitalsignage.ai','content-type':'text/plain','user-agent':'Mozilla/5.0'},body:JSON.stringify(ping)});const r=await onRequest({request,env:e});assert.equal(r.status,204);assert.equal(r.headers.get('access-control-allow-origin'),'https://www.digitalsignage.ai');assert.equal((await snapshot(e)).online,1);assert.equal((await onRequest({request:new Request(req.url,{method:'POST',headers:{Origin:'https://evil.test'},body:JSON.stringify(ping)}),env:e})).status,403)});
