import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {asegurarDirectorio,cookieDeSesion,sesionCompleta,returnToSeguro} from '../functions/_webmaster-gate.js';
import {ensureRegistry,commercialCatalog,validateVenue,safeConnection,SEEDS} from '../functions/_xpace-registry.js';
import {issueAccess,digest} from '../functions/_xpace-auth.js';
import {onRequestGet as context,onRequestOptions as options} from '../functions/api/xpace/context.js';
import {onRequestGet as demos} from '../functions/api/xpace/demos.js';
import {onRequestPost as save,onRequestGet as registry} from '../functions/api/xpace/registry.js';
import {onRequestPost as connect,onRequestDelete as disconnect} from '../functions/api/xpace/connect.js';
class Statement{constructor(s){this.s=s;this.v=[]}bind(...v){this.v=v;return this}first(){return this.s.get(...this.v)||null}all(){return{results:this.s.all(...this.v)}}run(){return{success:true,meta:this.s.run(...this.v)}}}
class D1{constructor(){this.db=new DatabaseSync(':memory:')}prepare(sql){return new Statement(this.db.prepare(sql))}async batch(ss){return ss.map(s=>s.run())}}
const origin='https://www.admira.store';
async function setup(){const env={AUTH_DB:new D1,WEBMASTER_SIGNING_KEY:'test-xpace'};await asegurarDirectorio(env);await ensureRegistry(env);return env;}
async function user(env,email,keys,kind='team'){await env.AUTH_DB.prepare("INSERT INTO admiranext_users(email,display_name,role,status,session_version,created_at,updated_at,account_kind) VALUES(?,?,'viewer','active',1,1,1,?)").bind(email,'Reader',kind).run();for(const key of keys)await env.AUTH_DB.prepare('INSERT INTO admiranext_user_projects VALUES(?,?,1,?)').bind(email,key,'test').run();return{email,session_version:1};}
async function auth(env){const u=await env.AUTH_DB.prepare("SELECT * FROM admiranext_users WHERE email='csilva@admira.com'").first();const cookie=(await cookieDeSesion(env,u)).split(';')[0];const me=await sesionCompleta(new Request('https://www.admiranext.com/api/session',{headers:{cookie}}),env);return{cookie,csrf:me.csrf,me};}
const req=(path,method,headers={},body)=>new Request('https://www.admiranext.com'+path,{method,headers,body:body?JSON.stringify(body):undefined});
const api=(token,client=origin)=>req('/api/xpace/context','GET',{origin:client,authorization:'Bearer '+token});
async function data(env,u){const access=await issueAccess(env,u,origin);const response=await context({request:api(access.token),env});return{access,response,body:await response.json()};}
async function mutation(env,body){const a=await auth(env);return save({request:req('/api/xpace/registry','POST',{cookie:a.cookie,origin:'https://www.admiranext.com','X-Admira-CSRF':a.csrf},body),env});}

test('public demos expose the sample scenes plus Altadis and Sneakers Store without the commercial directory',async()=>{const r=demos({request:req('/api/xpace/demos','GET')});const d=await r.json();assert.equal(d.demo,true);assert.equal(d.projects.length,5);assert.ok(d.projects.some(p=>p.id==="sneakers-store"));assert.ok(d.venues.every(v=>v.demo));assert.equal(r.headers.get('access-control-allow-origin'),'*');assert.equal((await context({request:api('0'.repeat(64)),env:await setup()})).status,401);});
test('commercial grants are distinct from software grants and filtered server-side',async()=>{const env=await setup();let d=await data(env,await user(env,'reader@test.com',['commercial:starbucks']));assert.deepEqual(d.body.projects.map(p=>p.id),['starbucks']);assert.deepEqual(d.body.venues.map(v=>v.id),['alsea-sbux-021']);assert.equal(d.body.user.email,undefined);d=await data(env,await user(env,'software@test.com',['starbucks','xpaceos']));assert.deepEqual(d.body.projects,[]);assert.deepEqual(d.body.venues,[]);});
test('read token is client-bound, cannot substitute for central administration, and supports revocation',async()=>{const env=await setup(),u=await user(env,'readonly@test.com',['commercial:starbucks']),{access}=await data(env,u);assert.equal((await context({request:api(access.token,'https://www.xpaceos.com'),env})).status,401);assert.equal((await context({request:api(access.token,'https://evil.example'),env})).status,401);assert.equal((await registry({request:api(access.token),env})).status,403);assert.equal((await disconnect({request:req('/api/xpace/connect','DELETE',{origin,authorization:'Bearer '+access.token}),env})).status,200);assert.equal((await context({request:api(access.token),env})).status,401);});
test('changes to user permissions and suspension cut existing tokens immediately',async()=>{const env=await setup(),u=await user(env,'revoke@test.com',['commercial:starbucks']),{access}=await data(env,u);await env.AUTH_DB.prepare('DELETE FROM admiranext_user_projects WHERE user_email=?').bind(u.email).run();assert.deepEqual((await(await context({request:api(access.token),env})).json()).projects,[]);await env.AUTH_DB.prepare('UPDATE admiranext_users SET session_version=2 WHERE email=?').bind(u.email).run();assert.equal((await context({request:api(access.token),env})).status,401);u.session_version=2;const next=await issueAccess(env,u,origin);await env.AUTH_DB.prepare("UPDATE admiranext_users SET status='suspended' WHERE email=?").bind(u.email).run();assert.equal((await context({request:api(next.token),env})).status,401);});
test('expiry and contracted app are enforced for guests',async()=>{const env=await setup(),u=await user(env,'guest@test.com',['commercial:starbucks'],'guest');await assert.rejects(issueAccess(env,u,origin));await env.AUTH_DB.prepare("INSERT INTO admiranext_user_apps VALUES(?,'xpaceos',1,'test')").bind(u.email).run();const {access}=await data(env,u);await env.AUTH_DB.prepare('UPDATE admiranext_xpace_access SET expires_at=1 WHERE token_hash=?').bind(await digest(access.token)).run();assert.equal((await context({request:api(access.token),env})).status,401);const other=await issueAccess(env,u,origin);await env.AUTH_DB.prepare('UPDATE admiranext_users SET expires_at=1 WHERE email=?').bind(u.email).run();assert.equal((await context({request:api(other.token),env})).status,401);});
test('admin can register projects and explicit venues; disabled venues remain absent and seeds do not overwrite',async()=>{const env=await setup();assert.equal((await mutation(env,{kind:'project',id:'new-brand',name:'New brand',circuit:'new_circuit'})).status,200);assert.equal((await commercialCatalog(env)).find(p=>p.key==='commercial:new-brand').parent_key,'commercial-projects');const v={kind:'venue',id:'new-store-01',project_id:'new-brand',name:'Explicit store',xpace_url:'https://www.xpaceos.com/admira-xp/?autostart=cafeteria',enabled:true};assert.equal((await mutation(env,v)).status,200);const u=await user(env,'root@test.com',['commercial-projects']);let d=await data(env,u);assert.equal(d.body.projects.length,SEEDS.length+1);assert.ok(d.body.venues.some(v=>v.id==='new-store-01'));assert.equal((await mutation(env,{...v,enabled:false})).status,200);d=await data(env,u);assert.ok(!d.body.venues.some(v=>v.id==='new-store-01'));const audit=await env.AUTH_DB.prepare("SELECT action FROM admiranext_xpace_audit WHERE target_id='new-store-01'").all();assert.equal(audit.results.length,2);assert.equal((await mutation(env,{...v,project_id:'starbucks'})).status,422);assert.equal((await mutation(env,{kind:'project',id:'starbucks',name:'Renamed',circuit:'wrong'})).status,422);});
test('registry writes and token creation require existing cookie plus same-origin CSRF',async()=>{const env=await setup(),a=await auth(env),body={kind:'project',id:'unsafe',name:'Unsafe',circuit:'unsafe'};for(const headers of [{cookie:a.cookie},{cookie:a.cookie,origin:'https://evil.example','X-Admira-CSRF':a.csrf}])assert.equal((await save({request:req('/api/xpace/registry','POST',headers,body),env})).status,403);assert.equal((await connect({request:req('/api/xpace/connect','POST',{cookie:a.cookie,origin:'https://www.admiranext.com','X-Admira-CSRF':a.csrf},{origin:'https://evil.example'}),env})).status,422);});
test('venue URL validation rejects arbitrary sites, credentials and leaked query tokens',()=>{const projects=[{id:'starbucks',circuit:'alsea_starbucks'}],base={id:'test-store',project_id:'starbucks',name:'Store',enabled:true};for(const xpace_url of ['http://www.xpaceos.com/admira-xp/?autostart=xtanco','https://evil.example/admira-xp/?autostart=xtanco','https://user:secret@www.xpaceos.com/admira-xp/?autostart=xtanco','https://www.xpaceos.com/admira-xp/?autostart=xtanco&token=secret','https://www.xpaceos.com/admira-xp/?autostart=xtanco&project=jti'])assert.throws(()=>validateVenue({...base,xpace_url},projects));});
test('login return only accepts validated client origin and state, never an arbitrary redirect',()=>{const path='/xpace/connect?'+new URLSearchParams({origin,state:'a'.repeat(32)});assert.equal(returnToSeguro(path),path);for(const p of [path+'&next=https://evil.example',path.replace('admira.store','evil.example'),'/xpace/connect?origin='+origin+'&state=short','//evil.example']){assert.equal(safeConnection(p),null);assert.equal(returnToSeguro(p),'/webmaster');}assert.equal(returnToSeguro('/xpace/manage'),'/xpace/manage');});
test('CORS preflight is allowlisted and does not grant credentials or admin writes',()=>{const r=options({request:req('/api/xpace/context','OPTIONS',{origin})});assert.equal(r.status,204);assert.equal(r.headers.get('access-control-allow-credentials'),null);assert.doesNotMatch(r.headers.get('access-control-allow-methods'),/POST/);assert.equal(options({request:req('/api/xpace/context','OPTIONS',{origin:'https://evil.example'})}).status,403);});

test('single-use proof-of-possession exchange survives a missing window opener and rejects replay/origin/verifier changes',async()=>{
 const {onRequestPost:link}=await import('../functions/api/xpace/link.js'),env=await setup(),a=await auth(env),state='b'.repeat(64),verifier='c'.repeat(64),challenge=await digest(verifier);
 const post=(client,body)=>link({request:req('/api/xpace/link','POST',{origin:client},body),env});
 assert.equal((await post(origin,{action:'begin',state,challenge})).status,201);
 assert.equal((await post(origin,{action:'begin',state,challenge})).status,409);
 assert.equal((await post(origin,{action:'claim',state,verifier})).status,202);
 assert.equal((await post(origin,{action:'claim',state,verifier:'d'.repeat(64)})).status,410);
 assert.equal((await post('https://www.xpaceos.com',{action:'claim',state,verifier})).status,410);
 const grant=await connect({request:req('/api/xpace/connect','POST',{cookie:a.cookie,origin:'https://www.admiranext.com','X-Admira-CSRF':a.csrf},{origin,state}),env});assert.equal(grant.status,200);assert.equal((await grant.json()).token,undefined);
 const claimed=await post(origin,{action:'claim',state,verifier});assert.equal(claimed.status,200);const access=await claimed.json();assert.match(access.token,/^[0-9a-f]{64}$/);assert.equal((await context({request:api(access.token),env})).status,200);
 assert.equal((await post(origin,{action:'claim',state,verifier})).status,410);
});
test('connection grant cannot be forged from client origin or reused after expiry',async()=>{
 const {onRequestPost:link}=await import('../functions/api/xpace/link.js'),env=await setup(),a=await auth(env),state='e'.repeat(64),verifier='f'.repeat(64);
 await link({request:req('/api/xpace/link','POST',{origin},{action:'begin',state,challenge:await digest(verifier)}),env});
 assert.equal((await connect({request:req('/api/xpace/connect','POST',{cookie:a.cookie,origin,'X-Admira-CSRF':a.csrf},{origin,state}),env})).status,403);
 await env.AUTH_DB.prepare('UPDATE admiranext_xpace_links SET expires_at=1 WHERE state=?').bind(state).run();
 assert.equal((await connect({request:req('/api/xpace/connect','POST',{cookie:a.cookie,origin:'https://www.admiranext.com','X-Admira-CSRF':a.csrf},{origin,state}),env})).status,410);
});
test('central logout revokes existing read access as well as clearing cookies',async()=>{const {onRequestPost:logout}=await import('../functions/webmaster/logout.js'),env=await setup(),a=await auth(env),access=await issueAccess(env,a.me,origin);const response=await logout({request:req('/webmaster/logout','POST',{cookie:a.cookie,origin:'https://www.admiranext.com','X-Admira-CSRF':a.csrf}),env});assert.equal(response.status,200);assert.equal((await context({request:api(access.token),env})).status,401);});

test('admira.biz y clearchannel.tv (mismo backoffice que admira.app) pueden enlazar y leer, y solo con su propio token',async()=>{
 const {CLIENT_ORIGINS}=await import('../functions/_xpace-registry.js');
 for(const o of ['https://www.admira.biz','https://admira.biz','https://www.clearchannel.tv','https://clearchannel.tv'])assert.ok(CLIENT_ORIGINS.has(o),o);
 for(const o of ['https://admira.biz.evil.test','http://www.admira.biz','https://xadmira.biz','https://clearchannel.tv.evil.test'])assert.equal(CLIENT_ORIGINS.has(o),false,o);
 for(const client of ['https://www.admira.biz','https://www.clearchannel.tv']){
  const env=await setup(),u=await user(env,'biz-'+client.length+'@test.com',['commercial:starbucks']);
  const access=await issueAccess(env,u,client);
  const ok=await context({request:api(access.token,client),env});assert.equal(ok.status,200,client);
  // El token queda ligado a su origen: desde otro cliente no vale.
  assert.equal((await context({request:api(access.token,'https://www.admira.store'),env})).status,401,client);
  const pre=options({request:req('/api/xpace/link','OPTIONS',{origin:client})});assert.equal(pre.status,204);assert.equal(pre.headers.get('access-control-allow-credentials'),null);
 }
});

test('Sneakers Store accepts only its own explicit category URL and venue identity',()=>{const p=[{id:'sneakers-store',circuit:'sneakerstore'}],v={id:'sneakers-store-santa-rosa-19',project_id:'sneakers-store',name:'Sneakers Store',enabled:true,xpace_url:'https://www.admira.store/xpacios/sneakerstore/?loc=sneakers-store-santa-rosa-19'};assert.equal(validateVenue(v,p).project_id,'sneakers-store');for(const patch of [{id:'different'},{xpace_url:v.xpace_url.replace('sneakerstore/','other/')},{xpace_url:v.xpace_url+'&token=secret'}])assert.throws(()=>validateVenue({...v,...patch},p));});
