import {esc,presiteKey} from '../_presite.js';
function safeJson(value){return JSON.stringify(value).replace(/</g,'\\u003c')}
export async function onRequestGet({params,env}){
  const site=env.PRESENTATION_IDEAS&&await env.PRESENTATION_IDEAS.get(presiteKey(params.site),{type:'json'});
  if(!site)return new Response('Presite no encontrado',{status:404});
  const blocks=(site.blocks||[]).map((block,index)=>`<details class="ps-block" ${index===0?'open':''}><summary><span>${String(index+1).padStart(2,'0')}</span>${esc(block.title)}</summary><div class="ps-block-fields"><input name="eyebrow" value="${esc(block.eyebrow)}" aria-label="Etiqueta del bloque ${index+1}"><input name="title" value="${esc(block.title)}" aria-label="Título del bloque ${index+1}"><textarea name="body" aria-label="Contenido del bloque ${index+1}">${esc(block.body)}</textarea>${block.id==='cta'?`<input name="button" value="${esc(block.button)}" aria-label="Botón del bloque final">`:''}<input type="hidden" name="id" value="${esc(block.id)}"></div></details>`).join('');
  const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${esc(site.displayName)} · Estudio Presites</title><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/assets/presites-workspace.css?v=20260723-1"></head><body><div class="ps-shell"><header class="ps-topbar"><a class="ps-brand" href="/presites/"><i></i><span>ADmiraNeXT · Presites</span><small>Estudio</small></a><div class="ps-top-actions"><span class="ps-badge" id="presiteState">${site.status==='review-ready'?'Revisión preparada':'Borrador'}</span><a class="ps-top-link hide-mobile" href="/presites/${esc(site.slug)}/export">Exportar HTML</a><a class="ps-top-link" href="/presites/">Biblioteca</a></div></header><main class="ps-wrap"><section class="ps-hero"><div><p class="ps-kicker">Estudio editorial · ${esc(site.quality.toUpperCase())}</p><h1>${esc(site.displayName)}</h1><p class="ps-lead">Edita la narrativa por bloques, revisa cada breakpoint y conserva versiones antes de trasladar la dirección a producción real.</p></div><aside class="ps-hero-aside"><b>Publicación segura</b><p>El MVP solo simula la publicación. Nunca modifica dominios, DNS ni una home real.</p></aside></section><div class="ps-workspace"><section class="ps-panel"><h2>Bloques de la home</h2><p class="sub">Los seis bloques mantienen su orden y estructura; puedes cambiar toda la narrativa.</p><form id="presiteBlocks" class="ps-blocks">${blocks}</form><div class="ps-status" id="studioStatus" role="status"></div><div class="ps-actions"><button class="ps-button" id="loadVersions" type="button">Versiones</button><a class="ps-button" href="/presites/${esc(site.slug)}/export">Exportar</a><button class="ps-button warn" id="simulatePublish" type="button">Simular publicación</button><button class="ps-button primary" id="saveBlocks" type="button">Guardar cambios</button></div><div class="ps-version-list" id="versionList" hidden></div></section><section class="ps-panel ps-preview-shell"><div class="ps-preview-head"><span>Preview guardado · ${esc(site.language.toUpperCase())}</span><div class="ps-devices" aria-label="Tamaño del preview"><button type="button" data-device="desktop" aria-pressed="true" aria-label="Preview en escritorio">▱</button><button type="button" data-device="tablet" aria-pressed="false" aria-label="Preview en tableta">▯</button><button type="button" data-device="mobile" aria-pressed="false" aria-label="Preview en móvil">▯</button></div></div><div class="ps-preview-stage"><iframe class="ps-preview-frame" id="presitePreview" src="/presites/${esc(site.slug)}/preview" title="Preview de ${esc(site.displayName)}"></iframe></div></section></div></main></div><script>window.__PRESITE__=${safeJson(site)};</script><script src="/assets/presites-studio.js?v=20260723-1"></script></body></html>`;
  return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-robots-tag':'noindex, nofollow'}});
}
